version: 2.1 # https://circleci.com/docs/2.0/configuration-reference
jobs:
  build:
    resource_class: small
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16 # https://hub.docker.com/r/circleci/golang/ , https://hub.docker.com/_/golang?tab=description

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run unit tests
          command: |
            go test -v ./...
      - run: 
          name: Run code coverage
          command: |
            go test -coverprofile=c.out
            go tool cover -html=c.out -o coverage.html
            mv coverage.html $TEST_RESULTS  # extraneous example of using an environment variable

      - store_artifacts: # Upload test summary for display https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results: # Upload test results for display https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results

